on:
  push:
    paths:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: 'recursive'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate README
      run: |
        echo "| Folder Name | Reference | GLB File | Preview |" > README.md
        echo "| ----------- | --------- | -------- | ------- |" >> README.md
        for dir in $(ls); do
          if [ -d "$dir" ]; then
            for subdir in $(ls $dir); do
              if [ -d "$dir/$subdir" ]; then
                for file in $(ls "$dir/$subdir"); do
                  echo "| $dir | $subdir | [$file]($dir/$subdir/$file) | ![Preview]($dir/$subdir/preview.png) |" >> README.md
                done
              fi
            done
          fi
        done

    - name: Commit changes
      uses: actions/github-scripts@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_COMMITTER_NAME: GitHub Action
        GIT_COMMITTER_EMAIL: action@github.com
      with:
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with file list"
        git push



Godfrey Meyer
Invalid workflow file: .github/workflows/main.yml#L6
You have an error in your yaml syntax on line 6
This error is likely caused by a missing dash in the front of the line. In YAML, each item in a list should be preceded by a dash, like this:

bash
Copy code
on:
  push:
    paths:
      - files/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: 'recursive'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate README
      run: |
        echo "| Folder Name | Reference | GLB File | Preview |" > README.md
        echo "| ----------- | --------- | -------- | ------- |" >> README.md
        for dir in $(ls); do
          if [ -d "$dir" ]; then
            for subdir in $(ls $dir); do
              if [ -d "$dir/$subdir" ]; then
                for file in $(ls "$dir/$subdir"); do
                  echo "| $dir | $subdir | [$file]($dir/$subdir/$file) | ![Preview]($dir/$subdir/preview.png) |" >> README.md
                done
              fi
            done
          fi
        done

    - name: Commit changes
      uses: actions/github-scripts@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_COMMITTER_NAME: GitHub Action
        GIT_COMMITTER_EMAIL: action@github.com
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with file list"
        git push origin main
